name: 'Readme Linter'
description: 'Validates README files in modules using super-linter'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Load super-linter configuration
      shell: bash
      run: cat .github/super-linter.env >> "$GITHUB_ENV"

    - name: Lint Code Base
      id: lint
      uses: super-linter/super-linter/slim@v7.3.0
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Add Markdown Linter Report to Job Summary
      if: ${{ failure() && steps.lint.outcome == 'failure' }}
      shell: bash
      run: |
        if [ -f "$GITHUB_WORKSPACE/super-linter-output/super-linter/super-linter-parallel-stderr-MARKDOWN" ]; then
          echo "## Markdown Linter Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          sed 's|/github/workspace/||g' "$GITHUB_WORKSPACE/super-linter-output/super-linter/super-linter-parallel-stderr-MARKDOWN" >> $GITHUB_STEP_SUMMARY          echo '```' >> $GITHUB_STEP_SUMMARY
        fi
