name: 'Readme Linter'
description: 'Validates README files in modules using super-linter'

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Load super-linter configuration
      shell: bash
      run: cat .github/super-linter.env >> "$GITHUB_ENV"

    - name: Lint Code Base
      id: lint
      uses: super-linter/super-linter/slim@v7.3.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MARKDOWN_CONFIG_FILE: .markdown-lint.yml
        ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
        SAVE_SUPER_LINTER_OUTPUT: true

    - name: Debug Super-Linter Output
      if: always()
      shell: bash
      run: |
        echo "=== Debug: Super-Linter Output Directory Contents ==="
        if [ -d "$GITHUB_WORKSPACE/super-linter-output" ]; then
          find "$GITHUB_WORKSPACE/super-linter-output" -type f -print | while read -r file; do
            echo "=== Contents of ${file#$GITHUB_WORKSPACE/super-linter-output/} ==="
            cat "$file"
            echo ""
          done
        else
          echo "super-linter-output directory not found"
        fi

    - name: Add Markdown Linter Report to Job Summary
      if: failure()
      shell: bash
      run: |
        if [ -f "$GITHUB_WORKSPACE/super-linter-output/markdownlint.txt" ]; then
          echo "## Markdown Linter Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat "$GITHUB_WORKSPACE/super-linter-output/markdownlint.txt" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi
